# Görkem Abinin Puanlaması
görkem_players_data = [
    {
        "İsim": "Yağızcan",
        "Topu Kullanma Becerisi": 2,
        "Topsuz Alanda Hücum Becerisi": 4,
        "Birebir Savunma Becerisi": 5,
        "Takım Savunması Becerisi": 5,
    },
    {
        "İsim": "Samet",
        "Topu Kullanma Becerisi": 5,
        "Topsuz Alanda Hücum Becerisi": 5,
        "Birebir Savunma Becerisi": 1,
        "Takım Savunması Becerisi": 1,
    },
    {
        "İsim": "Oğuzcan",
        "Topu Kullanma Becerisi": 2,
        "Topsuz Alanda Hücum Becerisi": 2,
        "Birebir Savunma Becerisi": 1,
        "Takım Savunması Becerisi": 1,
    },
    {
        "İsim": "Muhammed",
        "Topu Kullanma Becerisi": 4,
        "Topsuz Alanda Hücum Becerisi": 2,
        "Birebir Savunma Becerisi": 2,
        "Takım Savunması Becerisi": 3,
    },
    {
        "İsim": "Nurullah",
        "Topu Kullanma Becerisi": 3,
        "Topsuz Alanda Hücum Becerisi": 4,
        "Birebir Savunma Becerisi": 5,
        "Takım Savunması Becerisi": 4,
    },
    {
        "İsim": "Yasin",
        "Topu Kullanma Becerisi": 3,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 2,
        "Takım Savunması Becerisi": 3,
    },
    {
        "İsim": "Oğuzhan",
        "Topu Kullanma Becerisi": 1,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 2,
        "Takım Savunması Becerisi": 3,
    },
    {
        "İsim": "Cihan",
        "Topu Kullanma Becerisi": 5,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 4,
        "Takım Savunması Becerisi": 3,
    },
    {
        "İsim": "İlker",
        "Topu Kullanma Becerisi": 3,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 3,
        "Takım Savunması Becerisi": 3,
    },
    {
        "İsim": "Cengiz",
        "Topu Kullanma Becerisi": 1,
        "Topsuz Alanda Hücum Becerisi": 1,
        "Birebir Savunma Becerisi": 4,
        "Takım Savunması Becerisi": 2,
    },
    {
        "İsim": "Kerem",
        "Topu Kullanma Becerisi": 3,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 3,
        "Takım Savunması Becerisi": 3,
    },
    {
        "İsim": "Emre",
        "Topu Kullanma Becerisi": 1,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 3,
        "Takım Savunması Becerisi": 2,
    },
    {
        "İsim": "Görkem",
        "Topu Kullanma Becerisi": 5,
        "Topsuz Alanda Hücum Becerisi": 5,
        "Birebir Savunma Becerisi": 4,
        "Takım Savunması Becerisi": 2,
    },
    {
        "İsim": "Reşat",
        "Topu Kullanma Becerisi": 5,
        "Topsuz Alanda Hücum Becerisi": 5,
        "Birebir Savunma Becerisi": 4,
        "Takım Savunması Becerisi": 3,
    },
    {
        "İsim": "Batu",
        "Topu Kullanma Becerisi": 5,
        "Topsuz Alanda Hücum Becerisi": 5,
        "Birebir Savunma Becerisi": 4,
        "Takım Savunması Becerisi": 2,
    },
    {
        "İsim": "Ali",
        "Topu Kullanma Becerisi": 3,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 2,
        "Takım Savunması Becerisi": 1,
    },
]

# Yağızın Puanlaması
yagiz_players_data = [
    {
        "İsim": "Yağızcan",
        "Topu Kullanma Becerisi": 2,
        "Topsuz Alanda Hücum Becerisi": 2,
        "Birebir Savunma Becerisi": 4,
        "Takım Savunması Becerisi": 5,
    },
    {
        "İsim": "Samet",
        "Topu Kullanma Becerisi": 4,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 2,
        "Takım Savunması Becerisi": 2,
    },
    {
        "İsim": "Oğuzcan",
        "Topu Kullanma Becerisi": 2,
        "Topsuz Alanda Hücum Becerisi": 2,
        "Birebir Savunma Becerisi": 1,
        "Takım Savunması Becerisi": 2,
    },
    {
        "İsim": "Muhammed",
        "Topu Kullanma Becerisi": 2,
        "Topsuz Alanda Hücum Becerisi": 2,
        "Birebir Savunma Becerisi": 3,
        "Takım Savunması Becerisi": 3,
    },
    {
        "İsim": "Nurullah",
        "Topu Kullanma Becerisi": 3,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 4,
        "Takım Savunması Becerisi": 4,
    },
    {
        "İsim": "Yasin",
        "Topu Kullanma Becerisi": 3,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 3,
        "Takım Savunması Becerisi": 3,
    },
    {
        "İsim": "Oğuzhan",
        "Topu Kullanma Becerisi": 2,
        "Topsuz Alanda Hücum Becerisi": 2,
        "Birebir Savunma Becerisi": 2,
        "Takım Savunması Becerisi": 2,
    },
    {
        "İsim": "Cihan",
        "Topu Kullanma Becerisi": 4,
        "Topsuz Alanda Hücum Becerisi": 2,
        "Birebir Savunma Becerisi": 3,
        "Takım Savunması Becerisi": 2,
    },
    {
        "İsim": "İlker",
        "Topu Kullanma Becerisi": 2,
        "Topsuz Alanda Hücum Becerisi": 2,
        "Birebir Savunma Becerisi": 4,
        "Takım Savunması Becerisi": 4,
    },
    {
        "İsim": "Cengiz",
        "Topu Kullanma Becerisi": 1,
        "Topsuz Alanda Hücum Becerisi": 2,
        "Birebir Savunma Becerisi": 2,
        "Takım Savunması Becerisi": 3,
    },
    {
        "İsim": "Kerem",
        "Topu Kullanma Becerisi": 2,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 2,
        "Takım Savunması Becerisi": 2,
    },
    {
        "İsim": "Emre",
        "Topu Kullanma Becerisi": 1,
        "Topsuz Alanda Hücum Becerisi": 2,
        "Birebir Savunma Becerisi": 4,
        "Takım Savunması Becerisi": 4,
    },
    {
        "İsim": "Görkem",
        "Topu Kullanma Becerisi": 5,
        "Topsuz Alanda Hücum Becerisi": 5,
        "Birebir Savunma Becerisi": 4,
        "Takım Savunması Becerisi": 2,
    },
    {
        "İsim": "Reşat",
        "Topu Kullanma Becerisi": 5,
        "Topsuz Alanda Hücum Becerisi": 5,
        "Birebir Savunma Becerisi": 2,
        "Takım Savunması Becerisi": 3,
    },
    {
        "İsim": "Batu",
        "Topu Kullanma Becerisi": 5,
        "Topsuz Alanda Hücum Becerisi": 5,
        "Birebir Savunma Becerisi": 4,
        "Takım Savunması Becerisi": 5,
    },
    {
        "İsim": "Ali",
        "Topu Kullanma Becerisi": 2,
        "Topsuz Alanda Hücum Becerisi": 3,
        "Birebir Savunma Becerisi": 2,
        "Takım Savunması Becerisi": 1,
    },
]
